2019-02-18 17:03:43,132 - selenium - INFO - 开始测试
2019-02-18 17:03:43,132 - selenium - ERROR - 报错信息 : 
Traceback (most recent call last):
  File "D:/Projects/Python Project/ufa_pc_test/util/opt_csv.py", line 59, in <module>
    r = 10/0
ZeroDivisionError: division by zero
2019-02-18 17:03:43,134 - selenium - INFO - end
